export const Colors = {
  background: '#FFF8F0',
  card: '#FFFFFF',
  accent: '#F5A623',
  accentLight: '#FFF3E0',
  border: '#F5E6D3',
  textPrimary: '#2D2D2D',
  textSecondary: '#8A7A6A',
  textTertiary: '#ADADAD',
  textBody: '#5A5A5A',
  success: '#5BAD6A',
  successLight: '#F0FAF0',
  info: '#4A9ECC',
  infoLight: '#E8F4FD',
  warning: '#E8803A',
  warningLight: '#FEF0E8',
  inputBg: '#F5F0EA',
  toggleOff: '#E0E0E0',
  divider: '#F5F0EA',
  handleBar: '#E0D9D1',
  subtle: '#DADADA',
};
